targets:
  Github:
    templates: [CoreDomain]
    templateAttributes:
      CoreName: Github
    # dependencies:
      # - target: Common_${platform}

  GithubData:
    templates: [CoreData]
    templateAttributes:
      CoreName: Github
    # dependencies:
      # - target: Common_${platform}
      # - target: CommonData_${platform}
      
  GithubTests:
    templates: [CoreTests]
    templateAttributes:
      CoreName: Github
      
