targets:
  Application:
    type: application
    platform: [iOS]
    sources: 
      - path: Sources
      - path: .
        includes: "*.swift"
      - path: Assets.xcassets
        buildPhase: resources

    settings: 
      base:
        INFOPLIST_FILE: Application/Info.plist
        PRODUCT_NAME: Scope
        PRODUCT_BUNDLE_IDENTIFIER: com.devyhan93.Scope
        DEVELOPMENT_TEAM: 89P34MPW47
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"

    dependencies:
      - target: Core/Github_${platform}
      - package: SPMProxy
        embed: true

schemes:
  Application_iOS:
    build:
      targets:
        Application_iOS: ["build", "archive"]
    run:
      targets:
        Application_iOS: ["run"]
    archive:
      targets:
        Application_iOS: ["archive"]

packages:
  SPMProxy:
    path: ./SPMProxy