name: Scope

options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  transitivelyLinkDependencies: true
  createIntermediateGroups: true
  developmentLanguage: ko
  deploymentTarget:
    iOS: 15.0 

parallelizeBuild: true
buildImplicitDependencies: true

projectReferences:      
  Core:
    path: ./Core/ScopeCore.xcodeproj

include: 
  - Application/project.yml