name: Scope

options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  transitivelyLinkDependencies: true
  createIntermediateGroups: true
  developmentLanguage: ko
  deploymentTarget:
    iOS: 15.0 

targetTemplates:
  CoreDomain:
    type: framework
    platform: [iOS]

parallelizeBuild: true
buildImplicitDependencies: true

include: 
  - Application/project.yml