name: ScopeCore

options:
  bundleIdPrefix: com.scope.core
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  transitivelyLinkDependencies: true
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    VALIDATE_WORKSPACE: true
  configs:
    Debug:
      EXCLUDED_ARCHS[sdk=iphonesimulator*]: $IOS_DEBUG_BUILD_EXCLUDE_ARCH
      OTHER_SWIFT_FLAGS: $(inherit) -DDEBUG -Xlinker -no_deduplicate

parallelizeBuild: true
buildImplicitDependencies: true
    
include:
  - Github/project.yml
  
targetTemplates:
  CoreDomain:
    type: framework
    platform: [iOS]
    sources:
      - path: ${CoreName}/Domain
    dependencies:
      - package: SPMProxy
    settings:
      base:
        PRODUCT_NAME: ${CoreName}
        INFOPLIST_FILE: Info-${platform}.plist

  CoreData:
    type: framework
    transitivelyLinkDependencies: true
    platform: [iOS]
    sources:
      - path: ${CoreName}/Data
    scheme:
      testTargets:
        - name: ${CoreName}Tests_${platform}
          randomExecutionOrder: true
          parallelizable: true
      gatherCoverageData: true
    dependencies:
      - target: ${CoreName}_${platform}
      - package: SPMProxy
    settings:
      base:
        PRODUCT_NAME: ${CoreName}Data
        INFOPLIST_FILE: Info-${platform}.plist

  CoreTests:
    type: bundle.unit-test
    platform: [iOS]
    sources:
      - path: ${CoreName}/Tests
    dependencies:
      - target: ${CoreName}_${platform}
      - target: ${CoreName}Data_${platform}
      - package: SPMProxy
    settings:
      base:
        PRODUCT_NAME: ${CoreName}Tests
        VALIDATE_WORKSPACE: true

packages:
  SPMProxy:
    path: ../SPMProxy